spring:
  web:
    resources:
      static-locations: classpath:/spring-frontend/
  thymeleaf:
    prefix: classpath:/spring-frontend/
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/store_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: store_app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS store_app_schema
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  error:
    whitelabel:
      enabled: false